// Mocks generated by Mockito 5.4.4 from annotations
// in latticelock/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:latticelock/core/services/history_service.dart' as _i4;
import 'package:latticelock/core/services/pdf_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePDFResult_0 extends _i1.SmartFake implements _i2.PDFResult {
  _FakePDFResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PDFService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPDFService extends _i1.Mock implements _i2.PDFService {
  MockPDFService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.PDFResult> generatePDF(_i2.PDFMetadata? metadata) =>
      (super.noSuchMethod(
        Invocation.method(
          #generatePDF,
          [metadata],
        ),
        returnValue: _i3.Future<_i2.PDFResult>.value(_FakePDFResult_0(
          this,
          Invocation.method(
            #generatePDF,
            [metadata],
          ),
        )),
      ) as _i3.Future<_i2.PDFResult>);

  @override
  _i3.Future<bool> downloadOrSharePDF(_i2.PDFResult? pdfResult) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadOrSharePDF,
          [pdfResult],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [HistoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryService extends _i1.Mock implements _i4.HistoryService {
  MockHistoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveEntry(_i4.PatternHistoryEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveEntry,
          [entry],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.PatternHistoryEntry>> getAllEntries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllEntries,
          [],
        ),
        returnValue: _i3.Future<List<_i4.PatternHistoryEntry>>.value(
            <_i4.PatternHistoryEntry>[]),
      ) as _i3.Future<List<_i4.PatternHistoryEntry>>);

  @override
  _i3.Future<List<_i4.PatternHistoryEntry>> getFilteredEntries(
          _i4.HistoryFilter? filter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFilteredEntries,
          [filter],
        ),
        returnValue: _i3.Future<List<_i4.PatternHistoryEntry>>.value(
            <_i4.PatternHistoryEntry>[]),
      ) as _i3.Future<List<_i4.PatternHistoryEntry>>);

  @override
  _i3.Future<_i4.PatternHistoryEntry?> getEntry(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntry,
          [id],
        ),
        returnValue: _i3.Future<_i4.PatternHistoryEntry?>.value(),
      ) as _i3.Future<_i4.PatternHistoryEntry?>);

  @override
  _i3.Future<void> deleteEntry(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<_i4.PatternHistoryEntry>> searchEntries(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEntries,
          [query],
        ),
        returnValue: _i3.Future<List<_i4.PatternHistoryEntry>>.value(
            <_i4.PatternHistoryEntry>[]),
      ) as _i3.Future<List<_i4.PatternHistoryEntry>>);
}
